-- Crear usuario (opcional)
-- CREATE USER COWORKING IDENTIFIED BY "StrongPass123";
-- GRANT CONNECT, RESOURCE TO COWORKING;

CREATE TABLE companies (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  nit VARCHAR2(20),
  contact_email VARCHAR2(100),
  phone VARCHAR2(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employees (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id NUMBER NOT NULL,
  first_name VARCHAR2(80) NOT NULL,
  last_name VARCHAR2(80) NOT NULL,
  document VARCHAR2(40) NOT NULL,
  role VARCHAR2(50),
  status VARCHAR2(10) DEFAULT 'ACTIVO' CHECK (status IN ('ACTIVO','INACTIVO')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE employees
  ADD CONSTRAINT fk_emp_company FOREIGN KEY (company_id) REFERENCES companies(id);

CREATE TABLE access_points (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(80) NOT NULL,
  location VARCHAR2(120)
);

CREATE TABLE access_logs (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id NUMBER NOT NULL,
  access_point_id NUMBER,
  direction VARCHAR2(3) CHECK (direction IN ('IN','OUT')) NOT NULL,
  occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE access_logs ADD CONSTRAINT fk_log_emp FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE access_logs ADD CONSTRAINT fk_log_ap FOREIGN KEY (access_point_id) REFERENCES access_points(id);

INSERT INTO companies(name, nit) VALUES ('Empresa Demo', '900123456');
INSERT INTO access_points(name, location) VALUES ('Torno Principal', 'Lobby');
COMMIT;
